Lesson 4
Nikolos123/Jango_new pull request #4
Opened 2021-03-05 21:37 UTC by Nikolos123

2021-03-05 21:38 UTC, Nikolos123 commented
Попла форма регистрации не пойму в чем дело.

2021-03-05 21:38 UTC, Nikolos123 commented
Поплыла

2021-03-09 10:01 UTC, Vokler requested changes

2021-03-09 10:01 UTC, Vokler commented on authapp/views.py
> +        form = UserLoginForm
Вы тут не вызвали класс, а просто передали ссылку на него

2021-03-09 10:01 UTC, Vokler commented on authapp/views.py
> +        form = UserRegisterForm
Тут так же - не вызвали класс

2021-03-09 16:51 UTC, Nikolos123 commented on authapp/views.py
> +        form = UserRegisterForm
Я вызвал но ничего не изменилась комит сделаю

2021-03-11 10:26 UTC, Vokler approved these changes

2021-03-11 10:26 UTC, merged